- Cargo.toml
I have no idea what I am doing here but it makes it go.
> Bubble up support for hyper's optional SSL in Cargo.

- .travis.yml
- Cargo.toml
- README.md
- src/client.rs
- src/error.rs
- src/lib.rs
Some notes justifying the choice of hyper 0.10 while the latest is 0.12, from https://github.com/apoelstra/rust-jsonrpc/pull/7
hyper 0.11 introduced a lot of complex asynchronous tokio stuff that we don't need; 0.12 made it optional (yay!) but didn't replace it with anything, meaning that we'd have to implement a lot of connection management ourselves. So our choices with hyper 0.12 are either to use the default options, bringing us up to 45 deps (lots of which are quickly-changing tokio), or re-implement a lot of old-hyper on our own.
With that in mind I'm simply going to upgrade from hyper 0.9 to 0.10; the main changes there are dropping SSL and supporting code, dropping cookie and some supporting code, fixing this security vuln which did not affect rust-jsonrpc hyperium/hyper@2603d78 , …
> Switch strason to serde_json; update hyper to 0.10

- src/client.rs
- src/lib.rs
While `Request` and `Response` might be useful, for a lot of use-cases they are just an implementation detail, that just gets in the way. I was wondering if they could be made non-private altogether, but I guess for some advanced uses, they might be necessary.
So the first patch makes some allocation savings, and second add a convenience function that allows forgetting that `Response` and `Request` exist at all. First patch have a longer commit explaining more about what's going on.
> Some ideas for improvement

- src/client.rs
- src/error.rs
- src/lib.rs
- src/util.rs
One drawback about this implementation is that the responses get lost when a batch error is produced. If retaining those is desired, suggestions are welcome.
> Support JSON-RPC batching

- src/client.rs
- src/error.rs
- src/lib.rs
- src/simple_http.rs
I had a bunch of changes when I noticed https://github.com/apoelstra/rust-jsonrpc/pull/38, so I cherry-picked @darosior's changes on top here.
This makes the Transport into a Box so that our client doesn't need to be generic. Because traits with generic methods are not allowed to be boxed, the trait methods had to be changed to `send_request` and `send_batch` with concrete types.
> Fixes to the Transport impl

- .github/workflows/rust.yml
- .travis.yml
Travis has stopped providing free CI, and all PRs are currently failing CI because of this. Github Action is a decent and easy to use alternatve.
> CI: Migrate to Github Actions

- .github/workflows/rust.yml
- README.md
However i can't compile master with `1.29` using:
```
cargo clean && cargo +1.29 generate-lockfile --verbose && cargo +1.29  update -p byteorder --precise "1.3.4" && cargo +1.29 update --package 'serde_json' --precise '1.0.39' && cargo +1.29 update --package 'serde_derive' --precise '1.0.98' && cargo +1.29 test
```
> README: 1.29 needs byteorder to be pined, too

- src/simple_http.rs
To instruct the server to close the connection after sending the response.
Keeping the connection open can get the client to hang if the server doesn't send a newline following the response. And `simple_http` doesn't support reusing the connection anyway, so no point in enabling keep-alive.
Before this change, I was unable to use `rust-jsonrpc` to communicate with the [Electrum wallet JSONRPC interface](https://electrum.readthedocs.io/en/latest/jsonrpc.html) (this is part of the Electrum *wallet*, different from the Electrum server JSONRPC interface), as it enables keep-alive by default and doesn't send a newline. It works with this PR.
> simple_http: Send the `Connection: Close` header

- Cargo.toml
- src/lib.rs
- src/simple_tcp.rs
- src/simple_uds.rs
This implements:
- A synchronous transport over `TcpListener` (i don't know of any application that use this but it was almost free to have)
- A synchronous Unix Domain Socket transport. This is useful for communicating with Bitcoin-related softwares other than `bitcoind`. For example, the [C-lightning daemon](https://github.com/ElementsProject/lightning/) and [Revault wallet daemon](https://github.com/revault/revaultd/) both expose an RPC interface over an UDS. This could allow applications such as https://github.com/laanwj/rust-clightning-rpc or https://github.com/revault/revault-gui to directly use this crate instead of relying on a modified version of it.
Unfortunately, there is a quirk. The "ip" listener from the stdlib works well on both Unix and Windows but the stdlib has no …
> More transport implementations

- src/simple_http.rs
Prevents a long timeout followed by an uninformative error message.
See also https://github.com/JeremyRubin/rust-jsonrpc-async/pull/2
> Don't attempt to read a body for auth error (401)

- Cargo.toml
- src/error.rs
- src/lib.rs
We do not need to use the `serde_derive` crate, there is a serde feature for this.
This is a replacement for #41 to save you doing it apoelstra.
Fix: #40
> Use serde derive feature instead of serde_derive crate

- src/simple_http.rs
Resolves: #62
Idea: 
After removing the auth part of we are left with either `<host_name>` or `<host_name_>:<port>` and `ToSocketAddr` [requires]( https://doc.rust-lang.org/std/net/trait.ToSocketAddrs.html) `&str` to be of form `<host_name_>:<port>`. First `to_socket_addrs()` call only succeeds if `after_auth` is well formed (`<host_name_>:<port>` ). If this fails we try to add the fallback port and call `to_socket_addrs()` again.
> Add IPv6 support

- CHANGELOG.md
- Cargo.toml
Add changelog notes and bump the version to v0.13.0
Perhaps we want to merge these PRs before release?
- https://github.com/apoelstra/rust-jsonrpc/pull/64
- https://github.com/apoelstra/rust-jsonrpc/pull/65
> Release tracking PR - v0.13.0

- Cargo.toml
- contrib/test.sh
- src/simple_http.rs
This is an attempt at #57. Which was a request for adding socks5 Proxy support into the http transport. 
This is useful to connect to RPC via Tor.
Summary:
- Adds a new feature flag `proxy` which does some extra steps to connect the `url` address via a `proxy` address.
- New fields are added inside `SimpleHttpTransport` which are only visible in `proxy` feature.
- The first PR contains a refactoring which takes the URL sanity checking logic to its own function. So that it can be used for the `proxy-addr` checking also.
- New constructor:  Client::http_proxy()
- Test covering basic behavior.
> Add SOCKS5 Proxy support in http transport

- .github/workflows/rust.yml
- contrib/test.sh
- src/client.rs
- src/simple_http.rs
- src/simple_tcp.rs
Clear all the clippy warnings introduce by a recent clippy update.
> Clear clippy warnings

- .github/workflows/rust.yml
- contrib/test.sh
It looks like there is some old LLVM/rustc/linker/??? bug that is preventing `syn` from building on MacOS and breaking our CI. This commit just disables it.
cc @tcharding can you pull this commit into #74 and then we'll merge that?
> WIP: try to fix CI on macos

- src/simple_http.rs
This is a quick and dirty attempt at fixing #67 that reuses the socket for multiple requests. It has few issues: 
- no error handing, client becomes unusable after encountering a single error
- `SimpleHttpTransport::request()` takes a `mut` reference to self, which cascades to all downstream users
- `TcpStream` is not `Clone`, therefore I had to remove the derive `Clone`
An alternate implementation based on `reqwest` (`hyper` seems too low-level because of the async stuff) wouldn't have these problems.  So I think I'm going to start on that. Just wanted so share this draft PR if anyone has feedback or has an idea on how to do this without `reqwest`.
> Reuse socket

- .gitignore
- fuzz/.gitignore
- fuzz/Cargo.toml
- fuzz/fuzz_targets/simple_http.rs
- fuzz/travis-fuzz.sh
- src/simple_http.rs
Tightens the mutex lifetime to improve performance. Basically we read all the data into a buffer and then unlock the mutex ASAP. We could be a bit more memory-efficient by using `serde_json::from_reader` to parse directly from the socket, but (a) that would make it harder to enforce the Content-length header; and (b) it'd hold the mutex for longer than necessary.
This commit also splits out the `HttpParseError` into several variants, which unfortunately makes this a breaking change. I think I can move that commit into its own PR if we want to get a minor rev out, but I don't think we care too much about that since this crate is pretty far to the edge of most dependency trees.
Adds a fuzz harness but doesn't integrate it into CI. Fixes a couple bugs I found while fuzzing locally.
> Simple HTTP cleanups and followup to #72

- src/simple_http.rs
Attempt at #79. Does not fix the issue, but will merge this anyway since it fixes an issue I've hit in other projects.
> simple_http: when writing fails, try (once) to reconnect the socket

- src/simple_http.rs
The `host` header for HTTP1.1 must be sent according to [mozilla specs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Host) and [RFC 9110](https://www.rfc-editor.org/rfc/rfc9110.html#name-host-and-authority).
The absence of a host header breaks the compatibility with [jsonrpsee](https://github.com/paritytech/jsonrpsee) HTTP server for example.
> Add `host` header to HTTP/1.1

- src/simple_http.rs
While upgrading from v0.11 to v0.14 I noticed that I started getting the following error when the server had disconnected the socket between requests, in our case due to the server idle timeout: 
```
Err(Transport(HttpResponseTooShort { actual: 0, needed: 12 }))
```
The same issue as is reported in https://github.com/apoelstra/rust-jsonrpc/issues/79 I believe.
I noticed https://github.com/apoelstra/rust-jsonrpc/pull/84 was an attempt to solve the problem and I think I found out why it didn't work as expected.
The client is using a `BufWriter` to write the `TcpStream` and unless you flush the buffer you will not see the broken pipe error in time in order to request a fresh connection.
This PR adds in the flushes and provides a unit test demonstrating that it fixes the issue. If you comment …
> simple_http: fix detecting broken pipe on request

- src/client.rs
- src/error.rs
- src/lib.rs
- src/simple_http.rs
- src/simple_tcp.rs
- src/simple_uds.rs
- src/util.rs
Licenses are boring as hell, so is are all the comments at the top of each file. This patch makes no comment on the merit of license comments in each file, rather this patch reduces the license comment to the minimum possible with no loss of meaning - an SPDX license identifier.
Note also please that we remove the "written by" comments as well for the following reasons (discussed recently on rust-bitcoin repo):
- they are not descriptive because many devs contributed
- they have a tendency to include the wrong date because of cut'n'pasta
- all this info is in the git history
ref: https://spdx.dev/ids/#how
> Introduce SPDX license identifiers

- src/lib.rs
- src/simple_http.rs
- src/simple_tcp.rs
- src/simple_uds.rs
Fix up the extern crates by doing:
- Remove edition 2015 use statements
- Feature guard `base64` re-export with the correct feature
- Re-export `serde` crate
- Add rustdoc to all three pub extern crates
> Add rustdoc to pub crate export

- src/lib.rs
So that downstream users can match against error variants.
I had to add minreq as a direct dependency to my project. Since we are using `minreq::Error` in one variant of `minreq_http::Error`, better let users directly access it as `minreq_http::minreq::Error`?
> minreq_http: re-export minreq dependency

- src/http/minreq_http.rs
It is useful for downstream users to be matching on errors that do not contain a valid JSONRPC error in the HTTP response body. One instance is if the HTTP server work queue depth is exceeded, as they probably want to retry the request later.
On such error we would return a JSON deserialization error, without exposing neither the HTTP status code nor the body of the response. This made it impossible to detect such transient errors.
Instead, introduce a new HttpError variant that gets returned when the requested is responded to by an error that does not contain valid JSON in its body.
See also: https://github.com/apoelstra/rust-jsonrpc/pull/94#discussion_r1245103898.
> minreq_http: return an HTTP error on error with no JSON in body

- CHANGELOG.md
- Cargo.toml
- src/http/minreq_http.rs
- src/http/simple_http.rs
To make #103 and #102 available downstream. Note i've successfully tested #103 in my software (detect and retry requests to bitcoind upon hitting a transient workqueue exceeded error). 
Updating the Error enum for minreq_http is an API break, so bump the major version.
> Release 0.16.0

- CHANGELOG.md
- README.md
- contrib/test.sh
- fuzz/fuzz_targets/minreq_http.rs
- fuzz/fuzz_targets/simple_http.rs
- integration_test/src/main.rs
- src/client.rs
- src/http/simple_http.rs
- src/lib.rs
- src/simple_tcp.rs
- src/simple_uds.rs
according to the jsonrpc spec params can be missing, or an object too.
close #107 
Breaking change
> Accept also None or Objects as params

- CHANGELOG.md
- Cargo.toml
changelog was already good (just fixed the date)
close #110
> Bump version to 0.17.0

- integration_test/src/main.rs
Clear all the `clippy` warnings from the `integration_test` crate. Done in preparation for re-writing CI to use the new `run_task` script. The last patch is bodgy.
> integration_test: Clear clippy warnings

- src/simple_uds.rs
The UNIX Stream example header comment had the same top comment mentioning `std::net::TcpListener`
> fix small copy/paste comment
